name: bird_classification
ckpt_path: ${oc.env:PROJECT_ROOT}/checkpoints/${name}/best_model.pth.ckpt
save_dir: ${oc.env:PROJECT_ROOT}/predictions/${name}/
data_dir: ${data.data_dir}
num_samples: 10
inference_glob_pattern: "*/*/*.jpg"
# data_dir: ${paths.data_dir}/bird_small