tensorboard:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: ${paths.output_dir}/logs
  name: "tensorboard_logs"
  version: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
