defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

trainer:
  max_epochs: 1
  accelerator: cpu
  devices: 1

model:
  _target_: pytorch_lightning.LightningModule

data:
  _target_: pytorch_lightning.LightningDataModule

hydra:
  output_subdir: null
  run:
    dir: .
