name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your default branch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.22"  # Pin to a specific version of uv

      - name: Set up Python 3.12
        run: uv python install --version 3.12 # Install Python 3.12 with uv

      - name: Install dependencies
        run: |
          UV_INDEX_URL=https://download.pytorch.org/whl/cpu \
          UV_EXTRA_INDEX_URL=https://pypi.org/simple \
          uv sync --all-extras --dev  # Install dependencies with uv

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest  # Run tests with coverage
          uv run coverage xml -o coverage.xml  # Generate coverage report in XML format

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.8.0  # Update to the latest version
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Use the token from secrets
          files: ./coverage.xml  # Specify the coverage report file
          fail_ci_if_error: true

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs after the CI job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/my-image:latest  # Adjust image name as needed

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/my-image:latest  # Push the image to GHCR
